### ISSUE TITLE
What is the strategy for free-riders in the experiment? 

### ISSUE THREAD

**Issue by Jh1009** [XinyiYS/CollaborativeFairFederatedLearning#2]
It seems like Plain free-rider(returns the same model parameters as the received ones)  from Federated_Learniner.py L76

**Comment by XinyiYS** [comment]
If you take a look at lines 44-51 in [`Participant.py`](https://github.com/XinyiYS/CollaborativeFairFederatedLearning/blob/b0bf3f3677cf2374b952821d2f6d8f1f9c48294c/pytorch/utils/Participant.py#L44), the free riders will add random noise to the model parameters before returning it instead of the exact same model.

The line 76 in [`Federated_Learner.py`](https://github.com/XinyiYS/CollaborativeFairFederatedLearning/blob/b0bf3f3677cf2374b952821d2f6d8f1f9c48294c/pytorch/utils/Federated_Learner.py#L76) is the initiatilization step of the free riders, specifically with the same model parameters as the server (and everyone else).

**Comment by Jh1009** [comment]
Ok I see,thanks for the hint
